# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

template-file-path: cfn/iac-replica.yaml
parameters:
  KMSReplicaStackName: stack-deployment-kms-replica
  PrimaryKmsKeyArn: arn:aws:kms:eu-central-1:992382418145:key/mrk-9888e66a1d1d4d4c8c92b2a3d3cd2b85
  OpenTofuRemoteBackendBucketName: dominik-wombacher-iac-opentofu
  OpenTofuRemoteBackendBucketNameReplica: dominik-wombacher-iac-opentofu-replica
  OpenTofuRemoteBackendReplicationRoleName: OpenTofuRemoteBackendReplicationRole
tags:
  Purpose: IaC
  Lifecycle: Active
  Environment: Production
  Creator: CloudFormation
  DoNotDelete: True
