# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

template-file-path: cfn/kms-replica.yaml
parameters:
  # NOTE: This ARN must be obtained from the primary KMS stack after it's deployed.
  # The primary key ARN is exported as KMSKeyForBackendEncryptionPrimary-KMSKeyBackendEncryptionArn
  KMSKeyBackendEncryptionPrimaryArn: ""
  BackendEncryptionKmsKeyAlias: backend-encryption
tags:
  Purpose: IaC
  Lifecycle: Active
  Environment: Production
  Creator: CloudFormation
  DoNotDelete: True
