# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

template-file-path: cfn/kms.yaml
parameters:
  BackendEncryptionKmsKeyAlias: backend-encryption
tags:
  Purpose: IaC
  Lifecycle: Active
  Environment: Production
  Creator: CloudFormation
  DoNotDelete: True
